import type { RouteId } from './lib/router';

export interface Presentation { eyebrow: string; intro: string; run: string; about: string; text: string; note: string; category: string; summary: string; caps: string[] }

export const PRESENTATION: Record<Exclude<RouteId, 'dashboard'>, Presentation> = {
  'qr-generator': { eyebrow: 'SHARE · QR CODE', intro: 'A code for your content', run: 'Generate QR code', about: 'Easy to scan, easy to share.', text: 'Choose text/link, Wi-Fi login, email, phone call, SMS, or a contact card. Download PNG for everyday use or SVG for sharp printing at any size.', note: 'A four-module white border keeps the code scannable. QR content, including Wi-Fi passwords, is not saved in drafts or activity.', category: 'Miscellaneous', summary: 'Create QR codes for links, Wi-Fi, and contacts.', caps: [] },
  'unlock-pdf': { eyebrow: 'DOCUMENTS · PDF', intro: 'An unlocked copy', run: 'Unlock PDF', about: 'Open your PDF without a password.', text: 'Enter a known opening or owner password to remove PDF encryption. Pages, selectable text, links and forms are kept without rendering pages to images.', note: 'The original stays untouched. Passwords are never saved. Rewriting a PDF invalidates digital signatures; review signed documents separately.', category: 'PDFs', summary: 'Remove a PDF password with the password you know.', caps: ['workers'] },
  'date-time': { eyebrow: 'DATES · TIMEZONES', intro: 'Time, in the format you need', run: 'Calculate', about: 'Time, in the format you need.', text: 'Unix timestamps use seconds or milliseconds since 1970-01-01T00:00:00Z. Select a timezone to show the date where you need it.', note: 'When daylight saving creates a missing or repeated local time, missing times are rejected and you can choose the earlier or later occurrence.', category: 'Miscellaneous', summary: 'Calculate dates, timestamps, and timezones.', caps: [] },
  'folder-sync': {"eyebrow":"FILES · RSYNC","intro":"Plan your folder sync","run":"Preview changes","about":"Preview first, sync locally.","text":"Choose source and destination paths, checksums, mirror mode and exclude patterns. Copy the dry-run command to review changes in your terminal, then run the sync command.","note":"Archive mode preserves times, permissions and symlinks. Sync can replace changed files; mirror also deletes destination-only files. Paths are checked by rsync when you run it.","category":"Command planners","summary":"Plan rsync previews and folder syncs.","caps":[]},
  'media-downloader': {"eyebrow":"MEDIA · YT-DLP","intro":"Plan a media download","run":"Preview command","about":"Save exactly what you need.","text":"Prepare a yt-dlp command for a single item or playlist, choose video or audio quality, and optionally save a time range.","note":"Run the command with yt-dlp and FFmpeg installed on your computer. Site support depends on your yt-dlp version; some sites also need a supported JavaScript runtime.","category":"Command planners","summary":"Plan video, audio, playlist or clip downloads.","caps":[]},
  'secure-copy': { eyebrow: 'FILES · SSH', intro: 'Plan a secure transfer', run: 'Preview transfer', about: 'Secure copy with your SSH client.', text: 'Prepare an upload or download for one file or a folder. Your local SSH client performs the transfer using your existing SSH setup.', note: 'Browsers cannot connect to SSH servers or use your SSH agent. No credentials are requested or stored here; this page only prepares a command.', category: 'Command planners', summary: 'Plan SCP transfers · local execution.', caps: [] },
  'media-converter': { eyebrow: 'MEDIA · FFMPEG', intro: 'A new format, a smaller file', run: 'Convert media', about: 'Give your media a new shape.', text: 'Convert a local file, extract audio, or trim a clip with single-thread FFmpeg WebAssembly. Progress is shown while it runs.', note: 'Large files are slow and limited by browser memory. The source file stays in place and a new file is downloaded.', category: 'Media, documents & images', summary: 'Convert, extract, or trim media.', caps: ['wasm', 'workers', 'ffmpeg'] },
  'document-converter': {"eyebrow":"DOCUMENTS · BROWSER","intro":"A format for your reader","run":"Convert document","about":"Readable documents in a new format.","text":"Convert selectable PDF text to EPUB or Markdown, and turn EPUB or Markdown into paginated PDF. Plain text, HTML and classic MOBI conversions remain available.","note":"PDF conversion reflows text. Images, original page layouts, OCR, protected PDFs and DRM are unsupported. Review multi-column text and tables after conversion.","category":"Media, documents & images","summary":"Convert PDF, EPUB, Markdown and other text formats.","caps":["pdfjs"]},
  'pdf-to-images': { eyebrow: 'DOCUMENTS · PDF.JS', intro: 'Sharp images from PDF pages', run: 'Export page images', about: 'From a page to an image.', text: 'Render all or selected PDF pages as PNG or JPEG at your chosen resolution. Images keep the original page numbers.', note: 'Higher DPI increases memory use and output size. Pages that would be too large are refused.', category: 'PDFs', summary: 'Export PDF pages as images.', caps: ['workers', 'pdfjs'] },
  'images-to-pdf': { eyebrow: 'DOCUMENTS · PDF-LIB', intro: 'Your images, page by page', run: 'Create PDF', about: 'A document from your images.', text: 'Arrange images into a PDF with one image per page. Match each image’s size, or fit them onto A4 or Letter pages.', note: 'Preview shows the page order. Source images are never modified.', category: 'PDFs', summary: 'Create a PDF from your images.', caps: [] },
  'merge-pdfs': { eyebrow: 'DOCUMENTS · PDF-LIB', intro: 'Your PDFs, in your order', run: 'Merge PDFs', about: 'Put the pieces together.', text: 'Combine two or more PDFs. Move them up or down, and optionally choose pages from each one.', note: 'Source PDFs stay untouched. Bookmarks and metadata are not copied; interactive forms may need review.', category: 'PDFs', summary: 'Combine PDFs in your chosen order.', caps: [] },
  'split-pdf': { eyebrow: 'DOCUMENTS · PDF-LIB', intro: 'The pages you need', run: 'Save PDF pages', about: 'Take your document apart.', text: 'Save one PDF per page, or collect selected pages into a single PDF. Download files individually or as a ZIP.', note: 'The source is preserved. Bookmarks and metadata are not copied; interactive forms may need review.', category: 'PDFs', summary: 'Split or extract PDF pages.', caps: [] },
  'compress-pdf': { eyebrow: 'DOCUMENTS · BROWSER', intro: 'A lighter PDF', run: 'Compress PDF', about: 'Less space, the same pages.', text: 'Use lossless compression to keep selectable text and image quality. Balanced and smaller-file modes rebuild visible pages as JPEG images for stronger compression.', note: 'Results depend on the source. If no size is saved, download an unchanged copy. Image modes flatten links and forms and remove searchable text. Rewriting invalidates digital signatures.', category: 'PDFs', summary: 'Reduce PDF file size.', caps: [] },
  'image-workshop': { eyebrow: 'IMAGES · CANVAS', intro: 'Make the image work for you', run: 'Export image', about: 'Everyday image adjustments.', text: 'Convert, resize, rotate, flip, and adjust color. The preview updates as you change settings.', note: 'Use Crop Image to choose a custom crop. The original stays untouched; your edits are saved as a new file.', category: 'Media, documents & images', summary: 'Resize, convert, and adjust images.', caps: [] },
  'crop-image': { eyebrow: 'IMAGES · CANVAS', intro: 'Keep the part you need', run: 'Export cropped image', about: 'See exactly what stays.', text: 'Choose the width and height to keep, then set where the crop starts from the left and top edges. The outline shows the kept area on the original image.', note: 'Measurements show pixels removed from every edge. Cropping preserves the original file and saves a separate image at the displayed dimensions.', category: 'Media, documents & images', summary: 'Crop with a preview and exact pixel measurements.', caps: [] },
};

export const GROUPS: [string, (keyof typeof PRESENTATION)[]][] = [
  ['Media, documents & images', ['media-converter', 'document-converter', 'image-workshop', 'crop-image']],
  ['PDFs', ['pdf-to-images', 'images-to-pdf', 'merge-pdfs', 'split-pdf', 'compress-pdf', 'unlock-pdf']],
  ['Command planners', ['folder-sync', 'media-downloader', 'secure-copy']],
  ['Miscellaneous', ['date-time', 'qr-generator']],
];
